from multithreading import run_multiple_cams
from sequential import run_multiple_cams as run_multiple_cams_sequential
from multithreading_no_imshow import run_tracker_in_thread as run_multiple_cams_no_imshow